### ISSUE TITLE
Readiness probe failed: MongoDB shell version v3.6.6 connecting to: mongodb://127.0.0.1:27017 2018-08-13T09:02:26.516+0000 W NETWORK [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused 

### ISSUE THREAD

**Issue by abhilash07** [containerum/containerum#32]
hi i deployed containerum on kuberntes cluster but  unexpectedly i am gettig mongo db error.

 Readiness probe failed: MongoDB shell version v3.6.6 connecting to: mongodb://127.0.0.1:27017 2018-08-13T09:02:26.516+0000 W NETWORK [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused 2018-08-13T09:02:26.516+0000 E QUERY [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed : connect@src/mongo/shell/mongo.js:251:13 @(connect):1:6 exception: connect failed
Back-off restarting failed container 

i deployed "helm install containerum/containerum --version 1.0.20-rc.2"

please refer mongodb and resource logs

[logs-from-resource-in-terrific-gorilla-resource-6796cf66bd-sptmz.txt](https://github.com/containerum/containerum/files/2282383/logs-from-resource-in-terrific-gorilla-resource-6796cf66bd-sptmz.txt)
[logs-from-terrific-gorilla-mongodb-in-terrific-gorilla-mongodb-6fbcb9bcbd-tgb4g.txt](https://github.com/containerum/containerum/files/2282384/logs-from-terrific-gorilla-mongodb-in-terrific-gorilla-mongodb-6fbcb9bcbd-tgb4g.txt)
![screen shot 2018-08-13 at 6 10 21 pm](https://user-images.githubusercontent.com/10971841/44023131-9b97dfd0-9f24-11e8-8766-17cf944b0980.png)
![screen shot 2018-08-13 at 6 09 54 pm](https://user-images.githubusercontent.com/10971841/44023133-9bc459a2-9f24-11e8-8962-ea3c7065257d.png)
<img width="683" alt="screen shot 2018-08-13 at 6 09 30 pm" src="https://user-images.githubusercontent.com/10971841/44023134-9bf5ce38-9f24-11e8-802b-d01d9df25120.png">
<img width="1304" alt="screen shot 2018-08-13 at 6 09 12 pm" src="https://user-images.githubusercontent.com/10971841/44023135-9c22adea-9f24-11e8-939c-12369a175875.png">

is there any sollution to overcome this error ?

Regards
Abhilash

**Comment by voskvv** [comment]
Hi @abhilash07 
could you please enclose 1) the yaml file for the MongoDB pod and 2) the contents of ```describe pod``` for MongoDB with events. 

Thanks.

**Comment by abhilash07** [comment]
@voskvv thanks for your quick response.  As you requested i attached 1) MongoDB  POD, Deployment yaml files & 2) i also describe the MongoDB pod with events. Thanks
[mongodb-pod.txt](https://github.com/containerum/containerum/files/2282867/mongodb-pod.txt)
[mongodb-deployment.txt](https://github.com/containerum/containerum/files/2282868/mongodb-deployment.txt)
[mongodb-pod-describe-pod.txt](https://github.com/containerum/containerum/files/2282869/mongodb-pod-describe-pod.txt)

**Comment by voskvv** [comment]
@abhilash07 We've checked the logs - it seems that your Kubernetes cluster is not functioning correctly. We can't say what exactly is not ok since there's not enough information. You can contact us on Telegram at https://t.me/containerum - we'll try to help you figure out what's wrong.

**Comment by abhilash07** [comment]
@voskvv, if you see in MongoDB logs you can see "ecurity: { authorization: "disabled" }," did you know how to enable the authorization ?

**Comment by abhilash07** [comment]
i also deployed on gke, but same error continues, any sollution for this problem

**Comment by voskvv** [comment]
@abhilash07 

1) can you reinstall Containerum with these flags?
```
helm repo up
helm install containerum/containerum --version 1.0.20-rc.2 --debug --dry-run
```
And then, please,  send us the Helm log that you will get during installation.

2) check IPv6:
test -f /proc/net/if_inet6 && echo "Running kernel is IPv6 ready"

**Comment by voskvv** [comment]
@abhilash07 
And what network plugin do you use? Is it Flannel, Calico or something else? Thanks.

**Comment by abhilash07** [comment]
@voskvv, here are helm logs for your reference.
[helm-debub.log](https://github.com/containerum/containerum/files/2288753/helm-debub.log)
[helm-debub-dry-run.log](https://github.com/containerum/containerum/files/2288754/helm-debub-dry-run.log)
I checked IPv6 its running sucessfully
![screenshot 8](https://user-images.githubusercontent.com/10971841/44123446-5593a56a-a063-11e8-9cc2-2da18ae7f194.png)
I my network plugin is default Flannel. Thanks.

**Comment by voskvv** [comment]
@abhilash07 We couldn't recreate the problem as yet. We tried it on Kubernetes v1.11.1 on Ubuntu 16.04.5 LTS an it worked. We are going to try it on GKE and run some new tests as well - probably they will help. Stay tuned!
