### ISSUE TITLE
stuck at pending mongodb 

### ISSUE THREAD

**Issue by ralphQi** [containerum/containerum#62]
kubectl get pods 

like this: 

binging-chimp-api-gateway-7788fb988b-n4kd5     1/1       Running             0          15m
binging-chimp-auth-59fb7d5698-qgg8l            1/1       Running             0          15m
binging-chimp-kube-66cfb8fcb6-htjsq            0/1       ContainerCreating   0          15m
binging-chimp-kube-importer-7f4dd84cf9-zbv8k   0/1       ContainerCreating   0          15m
binging-chimp-mail-5d6ffd6dc6-m49d7            1/1       Running             0          15m
binging-chimp-mongodb-7875948fc-8j85t          0/1       ContainerCreating   0          1m
binging-chimp-nodemetrics-6d5fff4dd6-4t82l     1/1       Running             0          15m
binging-chimp-permissions-99df5d45c-64k5h      1/1       Running             1          15m
binging-chimp-postgresql-6bb8b57c4b-pmq7b      1/1       Running             0          15m
binging-chimp-resource-5ff7cfd4dd-kt86m        0/1       CrashLoopBackOff    7          15m
binging-chimp-solutions-5566f895d6-8cc77       1/1       Running             1          15m
binging-chimp-ui-c88548686-5n98m               1/1       Running             0          15m
binging-chimp-user-manager-85f7858fd-52jfq     1/1       Running             1          15m
binging-chimp-volume-5db9b4c55b-9zp9p          1/1       Running             1          15m

And, sometime I install containerum, there is not ui component.

Someone help me please? Thanks!

**Comment by ralphQi** [comment]
Events:
  Type    Reason                 Age   From                         Message
  ----    ------                 ----  ----                         -------
  Normal  Scheduled              9m    default-scheduler            Successfully assigned famous-gerbil-mongodb-788988698c-m4nnj to docker-for-desktop
  Normal  SuccessfulMountVolume  9m    kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "data"
  Normal  SuccessfulMountVolume  9m    kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "default-token-8r7g5"
  Normal  Pulling                9m    kubelet, docker-for-desktop  pulling image "docker.io/bitnami/mongodb:3.6.6-debian-9"


BUT, I am pretty sure that I have "docker.io/bitnami/mongodb:3.6.6-debian-9" image on my disk.


ralph:archive ralph$ docker images |grep bitnami
bitnami/mongodb                            3.6.6-debian-9      37a693624814        6 weeks ago         410MB

**Comment by voskvv** [comment]
Hi!
Are the pods still in the "ContainerCreating"/"CrashLoopBackOff" status? 
We tried to replicate the problem, but everything works fine.

Please, check if the machine has enough resources. How much CPU and RAM does your machine have?
