### ISSUE TITLE
chars.containerum.io no longer available

### ISSUE THREAD

**Issue by anole1980** [containerum/containerum#90]
When I was trying to install it:
```
$ helm repo add containerum https://charts.containerum.io
Error: Looks like "https://charts.containerum.io" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 102: mapping values are not allowed in this context
```

Then, I tried to open the url in chrome, and I got a 404 and yellow hot air balloon!
What's happening? Is this project already dead?

**Comment by voskvv** [comment]
Hi,

The repo is temporarily unavailable, sorry for that. But the project is by no means dead, it is currently under redesign and development.
